hebrewLetterDict = {
    "א" : 'ALEPH',
    "ב" : 'BETH',
    "ג" : 'GIMMEL',
    "ד" : 'DALET',
    "ה" : 'HE',
    "ו" : 'VAV',
    "ז" : 'ZAYIN',
    "ח" : 'CHET',
    "ט" : 'TES',
    "י" : 'YOD',
    "ך" : 'FINAL KAPH',
    "כ" : 'KAPH',
    "ל" : 'LAMED',
    "ם" : 'FINAL MEM',
    "מ" : 'MEM',
    "ן" : 'FINAL NUN',
    "נ" : 'NUN',
    "ס" : 'SAMECH',
    "ע" : 'AYIN',
    "ף" : 'FINAL PE',
    "פ" : 'PE',
    "ץ" : 'FINAL TZADDI',
    "צ" : 'TZADDI',
    "ק" : 'QUF',
    "ר" : 'RESH',
    "ש" : 'SCHIN',
    "ת" : 'TAU'}
